### ISSUE TITLE
ascii UnicodeDecodeError

### ISSUE THREAD

**Issue by vanishing** [markjones112358/dmenu-extended#17]
First time executing dmenu_extended_run, I get:
```
Traceback (most recent call last):
  File "/usr/local/bin/dmenu_extended_run", line 11, in <module>
    dmenu_extended.run(debug)
  File "/usr/local/lib/python2.7/dist-packages/dmenu_extended.py", line 1120, in run
    cache = d.cache_load()
  File "/usr/local/lib/python2.7/dist-packages/dmenu_extended.py", line 510, in cache_load
    if self.cache_regenerate() == False:
  File "/usr/local/lib/python2.7/dist-packages/dmenu_extended.py", line 477, in cache_regenerate
    cache = self.cache_build()
  File "/usr/local/lib/python2.7/dist-packages/dmenu_extended.py", line 757, in cache_build
    for root, dirs , files in os.walk(watchdir, followlinks=follow_symlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb3 in position 1: ordinal not in range(128)
```

**Comment by vanishing** [comment]
Any update on this one though?

**Comment by markjones112358** [comment]
I'm looking into it now. Do you have Python3 on your system?

**Comment by vanishing** [comment]
Yes, I have both python2 and python3.

**Comment by markjones112358** [comment]
If you run dmenu-extended with Python 3 you should be okay.
Decoding that character (\0xb3 - a superscripted 3), found somewhere in your path, is tricky.
I'm sure there's a way, but the code broke inside posixpath.py which is a python module (not dmenu-extended).
I'll keep looking into it and let you know if I find a fix.

**Comment by vanishing** [comment]
Sounds good, once the initial cache is built, I can fun dmenu_extended_run fine. So I guess this is not too big of a problem for now.

**Comment by markjones112358** [comment]
I'm having trouble reproducing the error you were getting.
Could you paste the output of the command `locale` here for me please?

**Comment by vanishing** [comment]
Here you go:
```
└─ »»»  locale
LANG=en_US.utf8
LANGUAGE=en
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=en_US.utf8
```

**Comment by vanishing** [comment]
Hmm, interesting, I can't seem to reproduce this issue now.
I think it might be related to #15 , since the only change I applied is pulling the update and installing it.

**Comment by markjones112358** [comment]
Okay good. I'll leave this open for a while in case it happens to someone else, and as a reminder for me to undo the update and try to reproduce it that way.
Thanks for checking.

**Comment by vanishing** [comment]
No problem, thanks for all the help :)

**Comment by guiguid** [comment]
Hi, 
same thing on archlinux : 
`dmenu_extended_run 
Setting up dmenu-extended prefs files...
Plugins directory exists - skipped
Cache directory exists - skipped
prefs directory exists - skipped
Existing preferences file found, will not overwrite.
Traceback (most recent call last):
  File "/usr/bin/dmenu_extended_run", line 11, in <module>
    dmenu_extended.run(debug)
  File "/usr/lib/python3.4/site-packages/dmenu_extended.py", line 1121, in run
    cache = d.cache_load()
  File "/usr/lib/python3.4/site-packages/dmenu_extended.py", line 510, in cache_load
    if self.cache_regenerate() == False:
  File "/usr/lib/python3.4/site-packages/dmenu_extended.py", line 477, in cache_regenerate
    cache = self.cache_build()
  File "/usr/lib/python3.4/site-packages/dmenu_extended.py", line 668, in cache_build
    applications = self.scan_applications()
  File "/usr/lib/python3.4/site-packages/dmenu_extended.py", line 555, in scan_applications
    for line in f.readlines():
  File "/usr/lib/python3.4/codecs.py", line 699, in readlines
    return self.reader.readlines(sizehint)
  File "/usr/lib/python3.4/codecs.py", line 608, in readlines
    data = self.read()
  File "/usr/lib/python3.4/codecs.py", line 494, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 17: invalid start byte`

locales : 
`locale
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=`
