### ISSUE TITLE
Can't build cache, utf-8 error

### ISSUE THREAD

**Issue by vasiliev-vb** [markjones112358/dmenu-extended#28]
```bash
python3 -c "import dmenu_extended
  dmenu_extended.dmenu().cache_build()"
Setting up dmenu-extended prefs files...
Plugins directory exists - skipped
Cache directory exists - skipped
prefs directory exists - skipped
Existing preferences file found, will not overwrite.
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/lib/python3.5/site-packages/dmenu_extended.py", line 850, in cache_build
    self.cache_save(foldernames, file_cache_folders)
  File "/usr/lib/python3.5/site-packages/dmenu_extended.py", line 504, in cache_save
    f.write(item+"\n")
  File "/usr/lib/python3.5/codecs.py", line 718, in write
    return self.writer.write(data)
  File "/usr/lib/python3.5/codecs.py", line 376, in write
    data, consumed = self.encode(object, self.errors)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcbf' in position 32: surrogates not allowed
```

Simple workaround is to catch exceptions in `f.write(item+"\n")`, but maybe it should be fixed anywhere else?

**Comment by markjones112358** [comment]
Hi Vasiliev-eb,
This problem had been dealt with in the past but the code that dealt with it has since been overwritten. I've taken the old code (with exception handler) and re-implemented it. Could you let me know if this solves your problem.

Many thanks,

Mark

**Comment by vasiliev-vb** [comment]
Yes, this solved my problem, thanks.
